/* Generated by Yosys 0.29+34 (git sha1 57c9eb70f, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1684890651960/work=/usr/local/src/conda/yosys-0.29_35_g57c9eb70f -fdebug-prefix-map=/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* hdlname = "\\vga" *)
(* top =  1  *)
(* src = "vga.v:1.1-36.10" *)
module vga(clk, rst, led, vga_red, vga_green, vga_blue, vga_hsync, vga_vsync);
  (* src = "vga.v:14.1-34.4" *)
  wire _000_;
  wire _001_;
  (* src = "vga.v:26.20-26.24" *)
  wire _002_;
  (* src = "vga.v:26.20-26.24" *)
  wire _003_;
  (* src = "vga.v:26.20-26.24" *)
  wire _004_;
  (* src = "vga.v:26.20-26.24" *)
  wire _005_;
  (* src = "vga.v:27.24-27.32" *)
  wire _006_;
  (* src = "vga.v:27.24-27.32" *)
  wire _007_;
  (* src = "vga.v:27.24-27.32" *)
  wire _008_;
  (* src = "vga.v:27.24-27.32" *)
  wire _009_;
  (* force_downto = 32'd1 *)
  (* src = "vga.v:24.20-24.31|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 12 13 14 16 17 18 20 21 22 24" *)
  wire [24:0] _010_;
  (* force_downto = 32'd1 *)
  (* src = "vga.v:24.20-24.31|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/arith_map.v:112.23-112.24" *)
  wire [24:0] _011_;
  (* force_downto = 32'd1 *)
  (* src = "vga.v:24.20-24.31|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/arith_map.v:112.26-112.27" *)
  wire [24:0] _012_;
  (* force_downto = 32'd1 *)
  (* src = "vga.v:24.20-24.31|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/arith_map.v:170.23-170.24" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 12 13 14 16 17 18 20 21 22 24 25 26 27" *)
  wire [27:0] _013_;
  (* force_downto = 32'd1 *)
  (* src = "vga.v:24.20-24.31|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/arith_map.v:168.23-168.24" *)
  (* unused_bits = "25 26 27" *)
  wire [27:0] _014_;
  (* CLASS = "clock" *)
  (* CLOCK_SIGNAL = "yes" *)
  (* IS_PROPAGATED = 32'd1 *)
  (* NAME = "\\$iopadmap\\$clk" *)
  (* PERIOD = "10.000000" *)
  (* SOURCE_WIRES = "\\$iopadmap\\$clk" *)
  (* WAVEFORM = "0.000000 5.000000" *)
  wire _015_;
  wire _016_;
  (* force_downto = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _017_;
  (* force_downto = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _018_;
  (* force_downto = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire _019_;
  (* force_downto = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire _020_;
  (* force_downto = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire _021_;
  (* force_downto = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire _022_;
  (* force_downto = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire _023_;
  (* force_downto = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire _024_;
  (* force_downto = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire _025_;
  (* force_downto = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire _026_;
  (* CLASS = "clock" *)
  (* CLOCK_SIGNAL = "yes" *)
  (* IS_EXPLICIT = 32'd1 *)
  (* NAME = "sys_clk_pin" *)
  (* PERIOD = "10.000000" *)
  (* SOURCE_WIRES = "clk" *)
  (* WAVEFORM = "0.000000 5.000000" *)
  (* src = "vga.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "vga.v:12.12-12.19" *)
  wire [24:0] counter;
  (* src = "vga.v:4.22-4.25" *)
  output [3:0] led;
  wire [3:0] led;
  (* src = "vga.v:3.16-3.19" *)
  input rst;
  wire rst;
  (* src = "vga.v:7.22-7.30" *)
  output [3:0] vga_blue;
  wire [3:0] vga_blue;
  (* src = "vga.v:6.22-6.31" *)
  output [3:0] vga_green;
  wire [3:0] vga_green;
  (* src = "vga.v:8.16-8.25" *)
  output vga_hsync;
  wire vga_hsync;
  (* src = "vga.v:5.22-5.29" *)
  output [3:0] vga_red;
  wire [3:0] vga_red;
  (* src = "vga.v:9.16-9.25" *)
  output vga_vsync;
  wire vga_vsync;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h8000000000000000)
  ) _027_ (
    .I0(_017_[0]),
    .I1(_017_[1]),
    .I2(_017_[2]),
    .I3(_017_[3]),
    .I4(_017_[4]),
    .I5(_017_[5]),
    .O(_018_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h80)
  ) _028_ (
    .I0(counter[20]),
    .I1(counter[21]),
    .I2(counter[24]),
    .O(_017_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h1000)
  ) _029_ (
    .I0(counter[17]),
    .I1(counter[23]),
    .I2(counter[6]),
    .I3(counter[19]),
    .O(_017_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0001)
  ) _030_ (
    .I0(counter[8]),
    .I1(counter[9]),
    .I2(counter[10]),
    .I3(counter[15]),
    .O(_017_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h8000000000000000)
  ) _031_ (
    .I0(counter[11]),
    .I1(counter[12]),
    .I2(counter[13]),
    .I3(counter[14]),
    .I4(counter[16]),
    .I5(counter[18]),
    .O(_017_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0001)
  ) _032_ (
    .I0(counter[3]),
    .I1(counter[4]),
    .I2(counter[5]),
    .I3(counter[7]),
    .O(_017_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0100)
  ) _033_ (
    .I0(counter[0]),
    .I1(counter[1]),
    .I2(counter[2]),
    .I3(counter[22]),
    .O(_017_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'he)
  ) _034_ (
    .I0(_018_[0]),
    .I1(_018_[1]),
    .O(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _035_ (
    .I(_025_),
    .O(_002_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _036_ (
    .I(_020_),
    .O(_003_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _037_ (
    .I(_021_),
    .O(_004_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _038_ (
    .I(_024_),
    .O(_005_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _039_ (
    .I(_022_),
    .O(_006_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _040_ (
    .I(_023_),
    .O(_007_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _041_ (
    .I(_026_),
    .O(_008_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _042_ (
    .I(_019_),
    .O(_009_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _043_ (
    .I(_018_[1]),
    .O(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _044_ (
    .I(counter[0]),
    .O(_011_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:24.20-24.31|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _045_ (
    .CI(1'h0),
    .CO(_010_[3:0]),
    .CYINIT(1'h0),
    .DI(4'h1),
    .O(_012_[3:0]),
    .S({ counter[3:1], _011_[0] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:24.20-24.31|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _046_ (
    .CI(_010_[3]),
    .CO(_010_[7:4]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_012_[7:4]),
    .S(counter[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:24.20-24.31|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _047_ (
    .CI(_010_[7]),
    .CO(_010_[11:8]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_012_[11:8]),
    .S(counter[11:8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:24.20-24.31|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _048_ (
    .CI(_010_[11]),
    .CO(_010_[15:12]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_012_[15:12]),
    .S(counter[15:12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:24.20-24.31|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _049_ (
    .CI(_010_[15]),
    .CO(_010_[19:16]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_012_[19:16]),
    .S(counter[19:16])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:24.20-24.31|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _050_ (
    .CI(_010_[19]),
    .CO(_010_[23:20]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_012_[23:20]),
    .S(counter[23:20])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:24.20-24.31|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _051_ (
    .CI(_010_[23]),
    .CO({ _013_[27:25], _010_[24] }),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O({ _014_[27:25], _012_[24] }),
    .S({ 3'h0, counter[24] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _052_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[0]),
    .Q(counter[0]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _053_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[1]),
    .Q(counter[1]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _054_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[2]),
    .Q(counter[2]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _055_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[3]),
    .Q(counter[3]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _056_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[4]),
    .Q(counter[4]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _057_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[5]),
    .Q(counter[5]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _058_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[6]),
    .Q(counter[6]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _059_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[7]),
    .Q(counter[7]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _060_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[8]),
    .Q(counter[8]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _061_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[9]),
    .Q(counter[9]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _062_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[10]),
    .Q(counter[10]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _063_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[11]),
    .Q(counter[11]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _064_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[12]),
    .Q(counter[12]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _065_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[13]),
    .Q(counter[13]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _066_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[14]),
    .Q(counter[14]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _067_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[15]),
    .Q(counter[15]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _068_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[16]),
    .Q(counter[16]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _069_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[17]),
    .Q(counter[17]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _070_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[18]),
    .Q(counter[18]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _071_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[19]),
    .Q(counter[19]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _072_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[20]),
    .Q(counter[20]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _073_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[21]),
    .Q(counter[21]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _074_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[22]),
    .Q(counter[22]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _075_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[23]),
    .Q(counter[23]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _076_ (
    .C(_015_),
    .CE(1'h1),
    .D(_012_[24]),
    .Q(counter[24]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _077_ (
    .C(_015_),
    .CE(_018_[0]),
    .D(_002_),
    .Q(_025_),
    .R(_018_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _078_ (
    .C(_015_),
    .CE(_018_[0]),
    .D(_003_),
    .Q(_020_),
    .R(_018_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _079_ (
    .C(_015_),
    .CE(_018_[0]),
    .D(_004_),
    .Q(_021_),
    .R(_018_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _080_ (
    .C(_015_),
    .CE(_018_[0]),
    .D(_005_),
    .Q(_024_),
    .R(_018_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _081_ (
    .C(_015_),
    .CE(_018_[0]),
    .D(_006_),
    .Q(_022_),
    .R(_018_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _082_ (
    .C(_015_),
    .CE(_018_[0]),
    .D(_007_),
    .Q(_023_),
    .R(_018_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _083_ (
    .C(_015_),
    .CE(_018_[0]),
    .D(_008_),
    .Q(_026_),
    .R(_018_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _084_ (
    .C(_015_),
    .CE(_018_[0]),
    .D(_009_),
    .Q(_019_),
    .R(_018_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "vga.v:14.1-34.4|/home/marcobisky/LocalFiles/LIYUN/proj/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _085_ (
    .C(_015_),
    .CE(1'h1),
    .D(_000_),
    .Q(_016_),
    .R(1'h0)
  );
  (* keep = 32'd1 *)
  IBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("clk:E3")
  ) _086_ (
    .I(clk),
    .O(_015_)
  );
  (* keep = 32'd1 *)
  OBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("led[0]:H5")
  ) _087_ (
    .I(_025_),
    .O(led[0])
  );
  (* keep = 32'd1 *)
  OBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("led[1]:J5")
  ) _088_ (
    .I(_020_),
    .O(led[1])
  );
  (* keep = 32'd1 *)
  OBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("led[2]:T9")
  ) _089_ (
    .I(_021_),
    .O(led[2])
  );
  (* keep = 32'd1 *)
  OBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("led[3]:T10")
  ) _090_ (
    .I(_024_),
    .O(led[3])
  );
  (* keep = 32'd1 *)
  IBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("rst:D9")
  ) _091_ (
    .I(rst),
    .O(_018_[1])
  );
  (* keep = 32'd1 *)
  OBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("vga_blue[0]:B7")
  ) _092_ (
    .I(1'h0),
    .O(vga_blue[0])
  );
  (* keep = 32'd1 *)
  OBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("vga_blue[1]:C7")
  ) _093_ (
    .I(1'h0),
    .O(vga_blue[1])
  );
  (* keep = 32'd1 *)
  OBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("vga_blue[2]:D7")
  ) _094_ (
    .I(1'h0),
    .O(vga_blue[2])
  );
  (* keep = 32'd1 *)
  OBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("vga_blue[3]:D8")
  ) _095_ (
    .I(1'h0),
    .O(vga_blue[3])
  );
  (* keep = 32'd1 *)
  OBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("vga_green[0]:C6")
  ) _096_ (
    .I(1'h0),
    .O(vga_green[0])
  );
  (* keep = 32'd1 *)
  OBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("vga_green[1]:A5")
  ) _097_ (
    .I(1'h0),
    .O(vga_green[1])
  );
  (* keep = 32'd1 *)
  OBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("vga_green[2]:B6")
  ) _098_ (
    .I(1'h0),
    .O(vga_green[2])
  );
  (* keep = 32'd1 *)
  OBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("vga_green[3]:A6")
  ) _099_ (
    .I(1'h0),
    .O(vga_green[3])
  );
  (* keep = 32'd1 *)
  OBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("vga_hsync:B11")
  ) _100_ (
    .I(_016_),
    .O(vga_hsync)
  );
  (* keep = 32'd1 *)
  OBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("vga_red[0]:A3")
  ) _101_ (
    .I(_022_),
    .O(vga_red[0])
  );
  (* keep = 32'd1 *)
  OBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("vga_red[1]:B4")
  ) _102_ (
    .I(_023_),
    .O(vga_red[1])
  );
  (* keep = 32'd1 *)
  OBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("vga_red[2]:C5")
  ) _103_ (
    .I(_026_),
    .O(vga_red[2])
  );
  (* keep = 32'd1 *)
  OBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("vga_red[3]:A4")
  ) _104_ (
    .I(_019_),
    .O(vga_red[3])
  );
  (* keep = 32'd1 *)
  OBUF #(
    .IOSTANDARD("LVCMOS33"),
    .IO_LOC_PAIRS("vga_vsync:B12")
  ) _105_ (
    .I(_016_),
    .O(vga_vsync)
  );
  assign _011_[24:1] = counter[24:1];
  assign _013_[24:0] = _010_;
  assign _014_[24:0] = _012_;
endmodule
